package com.x930073498.lib.delegate.component;

import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.SharedElementCallback;
import android.support.v4.app.TaskStackBuilder;
import android.support.v7.view.ActionMode;
import android.support.v7.widget.Toolbar;
import android.view.KeyEvent;
import android.view.View;

import com.x930073498.lib.delegate.component.activity.data.ActivityResult;
import com.x930073498.lib.delegate.component.activity.data.Bundle_PersistableBundle;
import com.x930073498.lib.delegate.component.activity.data.DumpData;
import com.x930073498.lib.delegate.component.activity.data.FeatureIdMenu;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode_Option;
import com.x930073498.lib.delegate.component.activity.data.IntentRequestCode;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderForResultOption;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderOption;
import com.x930073498.lib.delegate.component.activity.data.KeyCode_KeyEvent;
import com.x930073498.lib.delegate.component.activity.data.OnCreateView_Name_Context_Attr;
import com.x930073498.lib.delegate.component.activity.data.OnCreateView_Name_Context_Attr_Parent;
import com.x930073498.lib.delegate.component.activity.data.PermissionsResult;
import com.x930073498.lib.delegate.component.activity.data.TitleColor;
import com.x930073498.lib.delegate.component.activity.data.ViewParams;

public final class Event<P> {
    public static final Event<Bundle> ON_CREATE = new Event<>();
    public static final Event<Integer> SET_THEME = new Event<>();
    public static final Event<Bundle> ON_POST_CREATE = new Event<>();
    public static final Event<Void> GET_SUPPORT_ACTION_BAR = new Event<>();
    public static final Event<Toolbar> SET_SUPPORT_ACTION_BAR = new Event<>();
    public static final Event<Void> GET_MENU_INFLATER = new Event<>();
    public static final Event<Integer> SET_CONTENT_VIEW_ID = new Event<>();
    public static final Event<View> SET_CONTENT_VIEW = new Event<>();
    public static final Event<ViewParams> SET_CONTENT_VIEW_VIEW_PARAMS = new Event<>();
    public static final Event<ViewParams> ADD_CONTENT_VIEW_VIEW_PARAMS = new Event<>();
    public static final Event<Configuration> ON_CONFIGURATION_CHANGED = new Event<>();
    public static final Event<Void> ON_POST_RESUME = new Event<>();
    public static final Event<Void> ON_START = new Event<>();
    public static final Event<Void> ON_STOP = new Event<>();
    public static final Event<Integer> FIND_VIEW_BY_ID = new Event<>();
    public static final Event<Void> ON_DESTROY = new Event<>();
    public static final Event<TitleColor> ON_TITLE_CHANGED = new Event<>();
    public static final Event<Integer> SUPPORT_REQUEST_WINDOW_FEATURE = new Event<>();
    public static final Event<Void> SUPPORT_INVALIDATE_OPTIONS_MENU = new Event<>();
    public static final Event<Void> INVALIDATE_OPTIONS_MENU = new Event<>();
    public static final Event<ActionMode> ON_SUPPORT_ACTION_MODE_STARTED = new Event<>();
    public static final Event<ActionMode> ON_SUPPORT_ACTION_MODE_FINISHED = new Event<>();
    public static final Event<ActionMode.Callback> ON_WINDOW_STARTING_SUPPORT_ACTION_MODE = new Event<>();
    public static final Event<ActionMode.Callback> START_SUPPORT_ACTION_MODE = new Event<>();
    public static final Event<TaskStackBuilder> ON_CREATE_SUPPORT_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<TaskStackBuilder> ON_PREPARE_SUPPORT_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<Void> ON_SUPPORT_NAVIGATE_UP = new Event<>();
    public static final Event<Void> GET_SUPPORT_PARENT_ACTIVITY_INTENT = new Event<>();
    public static final Event<Intent> SUPPORT_SHOULD_UP_RECREATE_TASK = new Event<>();
    public static final Event<Intent> SUPPORT_NAVIGATE_UP_TO = new Event<>();
    public static final Event<Void> ON_CONTENT_CHANGED = new Event<>();
    public static final Event<Void> GET_DRAWER_TOGGLE_DELEGATE = new Event<>();
    public static final Event<FeatureIdMenu> ON_MENU_OPENED = new Event<>();
    public static final Event<FeatureIdMenu> ON_PANEL_CLOSED = new Event<>();
    public static final Event<Bundle_PersistableBundle> ON_SAVE_INSTANCE_STATE = new Event<>();
    public static final Event<Void> GET_DELEGATE = new Event<>();
    public static final Event<KeyEvent> DISPATCH_KEY_EVENT = new Event<>();
    public static final Event<Void> GET_RESOURCES = new Event<>();
    public static final Event<KeyCode_KeyEvent> ON_KEY_DOWN = new Event<>();
    public static final Event<Void> OPEN_OPTIONS_MENU = new Event<>();
    public static final Event<Void> CLOSE_OPTIONS_MENU = new Event<>();
    public static final Event<ActivityResult> ON_ACTIVITY_RESULT = new Event<>();
    public static final Event<Void> SUPPORT_FINISH_AFTER_TRANSITION = new Event<>();
    public static final Event<SharedElementCallback> SET_ENTER_SHARED_ELEMENT_CALLBACK = new Event<>();
    public static final Event<SharedElementCallback> SET_EXIT_SHARED_ELEMENT_CALLBACK = new Event<>();
    public static final Event<Void> SUPPORT_POSTPONE_ENTER_TRANSITION = new Event<>();
    public static final Event<Void> SUPPORT_START_POSTPONED_ENTER_TRANSITION = new Event<>();
    public static final Event<Boolean> ON_MULTI_WINDOW_MODE_CHANGED = new Event<>();
    public static final Event<Boolean> ON_PICTURE_IN_PICTURE_MODE_CHANGED = new Event<>();
    public static final Event<Void> GET_LIFECYCLE = new Event<>();
    public static final Event<FeatureIdMenu> ON_CREATE_PANEL_MENU = new Event<>();
    public static final Event<Void> ON_LOW_MEMORY = new Event<>();
    public static final Event<Void> ON_PAUSE = new Event<>();
    public static final Event<Intent> ON_NEW_INTENT = new Event<>();
    public static final Event<Void> ON_STATE_NOT_SAVED = new Event<>();
    public static final Event<Void> ON_RESUME = new Event<>();
    public static final Event<Void> ON_RESUME_FRAGMENTS = new Event<>();
    public static final Event<FeatureIdMenu> ON_PREPARE_PANEL = new Event<>();
    public static final Event<Void> ON_RETAIN_CUSTOM_NON_CONFIGURATION_INSTANCE = new Event<>();
    public static final Event<Void> GET_LAST_CUSTOM_NON_CONFIGURATION_INSTANCE = new Event<>();
    public static final Event<DumpData> DUMP = new Event<>();
    public static final Event<Fragment> ON_ATTACH_FRAGMENT = new Event<>();
    public static final Event<Void> GET_SUPPORT_FRAGMENT_MANAGER = new Event<>();
    public static final Event<Void> GET_SUPPORT_LOADER_MANAGER = new Event<>();
    public static final Event<IntentRequestCode> START_ACTIVITY_FOR_RESULT = new Event<>();
    public static final Event<PermissionsResult> ON_REQUEST_PERMISSIONS_RESULT = new Event<>();
    public static final Event<Fragment_Intent_RequestCode> START_ACTIVITY_FROM_FRAGMENT = new Event<>();
    public static final Event<Fragment_Intent_RequestCode_Option> START_ACTIVITY_FROM_FRAGMENT_OPTION = new Event<>();
    public static final Event<IntentSenderOption> START_INTENT_SENDER_FROM_FRAGMENT = new Event<>();
    public static final Event<OnCreateView_Name_Context_Attr> ON_CREATE_VIEW = new Event<>();
    public static final Event<OnCreateView_Name_Context_Attr_Parent> ON_CREATE_VIEW_WITH_PARENT = new Event<>();
    public static final Event<IntentSenderForResultOption> START_INTENT_SENDER_FOR_RESULT = new Event<>();
    public static final Event<Void> GET_INTENT = new Event<>();
    public static final Event<Intent> SET_INTENT = new Event<>();
    public static final Event<Void> GET_WINDOW_MANAGER = new Event<>();
    public static final Event<Void> GET_WINDOW = new Event<>();
    public static final Event<Void> GET_LOADER_MANAGER = new Event<>();
    public static final Event<Void> GET_CURRENT_FOCUS = new Event<>();


}
