package com.x930073498.lib.delegate.component;

import android.app.Activity;
import android.app.ActivityManager;
import android.app.PictureInPictureParams;
import android.app.assist.AssistContent;
import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.SharedElementCallback;
import android.support.v4.app.TaskStackBuilder;
import android.support.v7.view.ActionMode;
import android.support.v7.widget.Toolbar;
import android.transition.TransitionManager;
import android.view.DragEvent;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.SearchEvent;
import android.view.View;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityEvent;

import com.x930073498.lib.delegate.component.activity.data.ActionModeCallback_Integer;
import com.x930073498.lib.delegate.component.activity.data.ActivityCharSequence;
import com.x930073498.lib.delegate.component.activity.data.ActivityIntentSenderOption;
import com.x930073498.lib.delegate.component.activity.data.ActivityIntentSenderOptionWithBundle;
import com.x930073498.lib.delegate.component.activity.data.ActivityRequestCode;
import com.x930073498.lib.delegate.component.activity.data.ActivityResult;
import com.x930073498.lib.delegate.component.activity.data.Activity_Intent;
import com.x930073498.lib.delegate.component.activity.data.Activity_Intent_RequestCode;
import com.x930073498.lib.delegate.component.activity.data.Activity_Intent_RequestCode_Bundle;
import com.x930073498.lib.delegate.component.activity.data.AnimationDef;
import com.x930073498.lib.delegate.component.activity.data.Bitmap_Cavas;
import com.x930073498.lib.delegate.component.activity.data.Boolean_ComponentName;
import com.x930073498.lib.delegate.component.activity.data.Bundle_PersistableBundle;
import com.x930073498.lib.delegate.component.activity.data.ContextMenu_View_ContextMenuInfo;
import com.x930073498.lib.delegate.component.activity.data.Context_String;
import com.x930073498.lib.delegate.component.activity.data.DumpData;
import com.x930073498.lib.delegate.component.activity.data.FeatureIdMenu;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode_Option;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode_Support;
import com.x930073498.lib.delegate.component.activity.data.Fragment_Intent_RequestCode_Option_Support;
import com.x930073498.lib.delegate.component.activity.data.IntentRequestCode;
import com.x930073498.lib.delegate.component.activity.data.IntentRequestCodeFlags;
import com.x930073498.lib.delegate.component.activity.data.IntentRequestCodeOptions;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderConfig;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderConfigWithOptions;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderForResultOption;
import com.x930073498.lib.delegate.component.activity.data.IntentSenderOption;
import com.x930073498.lib.delegate.component.activity.data.BooleanMode_NewConfig;
import com.x930073498.lib.delegate.component.activity.data.Intent_Bundle;
import com.x930073498.lib.delegate.component.activity.data.Intent_String;
import com.x930073498.lib.delegate.component.activity.data.Intents_Bundle;
import com.x930073498.lib.delegate.component.activity.data.KeyCode_KeyEvent;
import com.x930073498.lib.delegate.component.activity.data.KeyCode_RepeatCount_KeyEvent;
import com.x930073498.lib.delegate.component.activity.data.KeyboardshortcutList_Menu_DeviceId;
import com.x930073498.lib.delegate.component.activity.data.OnCreateView_Name_Context_Attr;
import com.x930073498.lib.delegate.component.activity.data.OnCreateView_Name_Context_Attr_Parent;
import com.x930073498.lib.delegate.component.activity.data.OrderedBroadcastOption;
import com.x930073498.lib.delegate.component.activity.data.PermissionsResult;
import com.x930073498.lib.delegate.component.activity.data.Query_Bundle;
import com.x930073498.lib.delegate.component.activity.data.Search_Condition;
import com.x930073498.lib.delegate.component.activity.data.String_Integer;
import com.x930073498.lib.delegate.component.activity.data.String_Integer_CursorFactory;
import com.x930073498.lib.delegate.component.activity.data.String_Integer_CursorFactory_DatabaseErrorHandler;
import com.x930073498.lib.delegate.component.activity.data.Theme_Config;
import com.x930073498.lib.delegate.component.activity.data.TitleColor;
import com.x930073498.lib.delegate.component.activity.data.ViewParams;

public final class Event<P> {
    public static final Event<Bundle_PersistableBundle> ON_CREATE_PERSISTABLE = new Event<>();
    public static final Event<Integer> SET_THEME = new Event<>();
    public static final Event<Bundle_PersistableBundle> ON_POST_CREATE_PERSISTABLE = new Event<>();
    public static final Event<Void> GET_SUPPORT_ACTION_BAR = new Event<>();
    public static final Event<Toolbar> SET_SUPPORT_ACTION_BAR = new Event<>();
    public static final Event<Void> GET_MENU_INFLATER = new Event<>();
    public static final Event<Integer> SET_CONTENT_VIEW_ID = new Event<>();
    public static final Event<View> SET_CONTENT_VIEW = new Event<>();
    public static final Event<ViewParams> SET_CONTENT_VIEW_VIEW_PARAMS = new Event<>();
    public static final Event<ViewParams> ADD_CONTENT_VIEW_VIEW_PARAMS = new Event<>();
    public static final Event<Configuration> ON_CONFIGURATION_CHANGED = new Event<>();
    public static final Event<Void> ON_POST_RESUME = new Event<>();
    public static final Event<Void> ON_START = new Event<>();
    public static final Event<Void> ON_STOP = new Event<>();
    public static final Event<Integer> FIND_VIEW_BY_ID = new Event<>();
    public static final Event<Void> ON_DESTROY = new Event<>();
    public static final Event<TitleColor> ON_TITLE_CHANGED = new Event<>();
    public static final Event<Integer> SUPPORT_REQUEST_WINDOW_FEATURE = new Event<>();
    public static final Event<Void> SUPPORT_INVALIDATE_OPTIONS_MENU = new Event<>();
    public static final Event<Void> INVALIDATE_OPTIONS_MENU = new Event<>();
    public static final Event<ActionMode> ON_SUPPORT_ACTION_MODE_STARTED = new Event<>();
    public static final Event<ActionMode> ON_SUPPORT_ACTION_MODE_FINISHED = new Event<>();
    public static final Event<ActionMode.Callback> ON_WINDOW_STARTING_SUPPORT_ACTION_MODE = new Event<>();
    public static final Event<ActionMode.Callback> START_SUPPORT_ACTION_MODE = new Event<>();
    public static final Event<TaskStackBuilder> ON_CREATE_SUPPORT_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<TaskStackBuilder> ON_PREPARE_SUPPORT_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<Void> ON_SUPPORT_NAVIGATE_UP = new Event<>();
    public static final Event<Void> GET_SUPPORT_PARENT_ACTIVITY_INTENT = new Event<>();
    public static final Event<Intent> SUPPORT_SHOULD_UP_RECREATE_TASK = new Event<>();
    public static final Event<Intent> SUPPORT_NAVIGATE_UP_TO = new Event<>();
    public static final Event<Void> ON_CONTENT_CHANGED = new Event<>();
    public static final Event<Void> GET_DRAWER_TOGGLE_DELEGATE = new Event<>();
    public static final Event<FeatureIdMenu> ON_MENU_OPENED = new Event<>();
    public static final Event<FeatureIdMenu> ON_PANEL_CLOSED = new Event<>();
    public static final Event<Bundle_PersistableBundle> ON_SAVE_INSTANCE_STATE_PERSISTABLE = new Event<>();
    public static final Event<Void> GET_DELEGATE = new Event<>();
    public static final Event<KeyEvent> DISPATCH_KEY_EVENT = new Event<>();
    public static final Event<Void> GET_RESOURCES = new Event<>();
    public static final Event<KeyCode_KeyEvent> ON_KEY_DOWN = new Event<>();
    public static final Event<Void> OPEN_OPTIONS_MENU = new Event<>();
    public static final Event<Void> CLOSE_OPTIONS_MENU = new Event<>();
    public static final Event<ActivityResult> ON_ACTIVITY_RESULT = new Event<>();
    public static final Event<Void> SUPPORT_FINISH_AFTER_TRANSITION = new Event<>();
    public static final Event<SharedElementCallback> SET_ENTER_SHARED_ELEMENT_CALLBACK_SUPPORT = new Event<>();
    public static final Event<SharedElementCallback> SET_EXIT_SHARED_ELEMENT_CALLBACK_SUPPORT = new Event<>();
    public static final Event<Void> SUPPORT_POSTPONE_ENTER_TRANSITION = new Event<>();
    public static final Event<Void> SUPPORT_START_POSTPONED_ENTER_TRANSITION = new Event<>();
    public static final Event<Boolean> ON_MULTI_WINDOW_MODE_CHANGED = new Event<>();
    public static final Event<Boolean> ON_PICTURE_IN_PICTURE_MODE_CHANGED = new Event<>();
    public static final Event<Void> GET_LIFECYCLE = new Event<>();
    public static final Event<FeatureIdMenu> ON_CREATE_PANEL_MENU = new Event<>();
    public static final Event<Void> ON_LOW_MEMORY = new Event<>();
    public static final Event<Void> ON_PAUSE = new Event<>();
    public static final Event<Intent> ON_NEW_INTENT = new Event<>();
    public static final Event<Void> ON_STATE_NOT_SAVED = new Event<>();
    public static final Event<Void> ON_RESUME = new Event<>();
    public static final Event<Void> ON_RESUME_FRAGMENTS = new Event<>();
    public static final Event<FeatureIdMenu> ON_PREPARE_PANEL = new Event<>();
    public static final Event<Void> ON_RETAIN_CUSTOM_NON_CONFIGURATION_INSTANCE = new Event<>();
    public static final Event<Void> GET_LAST_CUSTOM_NON_CONFIGURATION_INSTANCE = new Event<>();
    public static final Event<DumpData> DUMP = new Event<>();
    public static final Event<Fragment> ON_ATTACH_FRAGMENT_SUPPORT = new Event<>();
    public static final Event<Void> GET_SUPPORT_FRAGMENT_MANAGER = new Event<>();
    public static final Event<Void> GET_SUPPORT_LOADER_MANAGER = new Event<>();
    public static final Event<IntentRequestCode> START_ACTIVITY_FOR_RESULT = new Event<>();
    public static final Event<PermissionsResult> ON_REQUEST_PERMISSIONS_RESULT = new Event<>();
    public static final Event<Fragment_Intent_RequestCode_Support> START_ACTIVITY_FROM_FRAGMENT_SUPPORT = new Event<>();
    public static final Event<Fragment_Intent_RequestCode_Option_Support> START_ACTIVITY_FROM_FRAGMENT_OPTION_SUPPORT = new Event<>();
    public static final Event<IntentSenderOption> START_INTENT_SENDER_FROM_FRAGMENT = new Event<>();
    public static final Event<OnCreateView_Name_Context_Attr> ON_CREATE_VIEW = new Event<>();
    public static final Event<OnCreateView_Name_Context_Attr_Parent> ON_CREATE_VIEW_WITH_PARENT = new Event<>();
    public static final Event<IntentSenderForResultOption> START_INTENT_SENDER_FOR_RESULT = new Event<>();
    public static final Event<Void> GET_INTENT = new Event<>();
    public static final Event<Intent> SET_INTENT = new Event<>();
    public static final Event<Void> GET_WINDOW_MANAGER = new Event<>();
    public static final Event<Void> GET_WINDOW = new Event<>();
    public static final Event<Void> GET_LOADER_MANAGER = new Event<>();
    public static final Event<Void> GET_CURRENT_FOCUS = new Event<>();
    public static final Event<Bundle> ON_CREATE = new Event<>();
    public static final Event<Bundle_PersistableBundle> ON_RESTORE_INSTANCE_STATE_PERSISTABLE = new Event<>();
    public static final Event<Bundle> ON_POST_CREATE = new Event<>();
    public static final Event<Bundle> ON_RESTORE_INSTANCE_STATE = new Event<>();
    public static final Event<Void> ON_RESTART = new Event<>();
    public static final Event<Void> IS_VOICE_INTERACTION = new Event<>();
    public static final Event<Void> IS_VOICE_INTERACTION_ROOT = new Event<>();
    public static final Event<Void> GET_VOICE_INTERACTOR = new Event<>();
    public static final Event<Void> IS_LOCAL_VOICE_INTERACTION_SUPPORTED = new Event<>();
    public static final Event<Bundle> START_LOCAL_VOICE_INTERACTION = new Event<>();
    public static final Event<Void> ON_LOCAL_VOICE_INTERACTION_STARTED = new Event<>();
    public static final Event<Void> ON_LOCAL_VOICE_INTERACTION_STOPPED = new Event<>();
    public static final Event<Void> STOP_LOCAL_VOICE_INTERACTION = new Event<>();
    public static final Event<Bundle> ON_SAVE_INSTANCE_STATE = new Event<>();
    public static final Event<Bitmap_Cavas> ON_CREATE_THUMBNAIL = new Event<>();
    public static final Event<Void> ON_USER_LEAVE_HINT = new Event<>();
    public static final Event<Void> ON_CREATE_DESCRIPTION = new Event<>();
    public static final Event<Bundle> ON_PROVIDE_ASSIST_DATA = new Event<>();
    public static final Event<AssistContent> ON_PROVIDE_ASSIST_CONTENT = new Event<>();
    public static final Event<KeyboardshortcutList_Menu_DeviceId> ON_PROVIDE_KEYBOARD_SHORTCUTS = new Event<>();
    public static final Event<Bundle> SHOW_ASSIST = new Event<>();
    public static final Event<Void> REPORT_FULLY_DRAWN = new Event<>();
    public static final Event<BooleanMode_NewConfig> ON_MULTI_WINDOW_MODE_CHANGED_CONFIG = new Event<>();
    public static final Event<Void> IS_IN_MULTI_WINDOW_MODE = new Event<>();
    public static final Event<BooleanMode_NewConfig> ON_PICTURE_IN_PICTURE_MODE_CHANGED_CONFIG = new Event<>();
    public static final Event<Void> IS_IN_PICTURE_IN_PICTURE_MODE = new Event<>();
    public static final Event<Void> ENTER_PICTURE_IN_PICTURE_MODE = new Event<>();
    public static final Event<PictureInPictureParams> ENTER_PICTURE_IN_PICTURE_MODE_PARAMS = new Event<>();
    public static final Event<PictureInPictureParams> SET_PICTURE_IN_PICTURE_PARAMS = new Event<>();
    public static final Event<Void> GET_MAX_NUM_PICTURE_IN_PICTURE_ACTIONS = new Event<>();
    public static final Event<Void> GET_CHANGING_CONFIGURATIONS = new Event<>();
    public static final Event<Void> GET_LAST_NON_CONFIGURATION_INSTANCE = new Event<>();
    public static final Event<Integer> ON_TRIM_MEMORY = new Event<>();
    public static final Event<Void> GET_FRAGMENT_MANAGER = new Event<>();
    public static final Event<android.app.Fragment> ON_ATTACH_FRAGMENT = new Event<>();
    public static final Event<Void> GET_ACTION_BAR = new Event<>();
    public static final Event<android.widget.Toolbar> SET_ACTION_BAR = new Event<>();
    public static final Event<Void> GET_CONTENT_TRANSITION_MANAGER = new Event<>();
    public static final Event<TransitionManager> SET_CONTENT_TRANSITION_MANAGER = new Event<>();
    public static final Event<Void> GET_CONTENT_SCENE = new Event<>();
    public static final Event<Boolean> SET_FINISH_ON_TOUCH_OUTSIDE = new Event<>();
    public static final Event<KeyCode_KeyEvent> ON_KEY_LONG_PRESS = new Event<>();
    public static final Event<KeyCode_KeyEvent> ON_KEY_UP = new Event<>();
    public static final Event<KeyCode_RepeatCount_KeyEvent> ON_KEY_MULTIPLE = new Event<>();
    public static final Event<KeyCode_KeyEvent> ON_KEY_SHORTCUT = new Event<>();
    public static final Event<MotionEvent> ON_TOUCH_EVENT = new Event<>();
    public static final Event<MotionEvent> ON_TRACKBALL_EVENT = new Event<>();
    public static final Event<MotionEvent> ON_GENERIC_MOTION_EVENT = new Event<>();
    public static final Event<Void> ON_USER_INTERACTION = new Event<>();
    public static final Event<WindowManager.LayoutParams> ON_WINDOW_ATTRIBUTES_CHANGED = new Event<>();
    public static final Event<Boolean> ON_WINDOW_FOCUS_CHANGED = new Event<>();
    public static final Event<Void> ON_ATTACHED_TO_WINDOW = new Event<>();
    public static final Event<Void> ON_DETACHED_FROM_WINDOW = new Event<>();
    public static final Event<Void> HAS_WINDOW_FOCUS = new Event<>();
    public static final Event<KeyEvent> DISPATCH_KEY_SHORTCUT_EVENT = new Event<>();
    public static final Event<MotionEvent> DISPATCH_TOUCH_EVENT = new Event<>();
    public static final Event<MotionEvent> DISPATCH_TRACKBALL_EVENT = new Event<>();
    public static final Event<MotionEvent> DISPATCH_GENERIC_MOTION_EVENT = new Event<>();
    public static final Event<AccessibilityEvent> DISPATCH_POPULATE_ACCESSIBILITY_EVENT = new Event<>();
    public static final Event<Integer> ON_CREATE_PANEL_VIEW = new Event<>();
    public static final Event<Menu> ON_CREATE_OPTIONS_MENU = new Event<>();
    public static final Event<Menu> ON_PREPARE_OPTIONS_MENU = new Event<>();
    public static final Event<MenuItem> ON_OPTIONS_ITEM_SELECTED = new Event<>();
    public static final Event<Void> ON_NAVIGATE_UP = new Event<>();
    public static final Event<Activity> ON_NAVIGATE_UP_FROM_CHILD = new Event<>();
    public static final Event<android.app.TaskStackBuilder> ON_CREATE_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<android.app.TaskStackBuilder> ON_PREPARE_NAVIGATE_UP_TASK_STACK = new Event<>();
    public static final Event<Menu> ON_OPTIONS_MENU_CLOSED = new Event<>();
    public static final Event<ContextMenu_View_ContextMenuInfo> ON_CREATE_CONTEXT_MENU = new Event<>();
    public static final Event<View> REGISTER_FOR_CONTEXT_MENU = new Event<>();
    public static final Event<View> UNREGISTER_FOR_CONTEXT_MENU = new Event<>();
    public static final Event<View> OPEN_CONTEXT_MENU = new Event<>();
    public static final Event<Void> CLOSE_CONTEXT_MENU = new Event<>();
    public static final Event<MenuItem> ON_CONTEXT_ITEM_SELECTED = new Event<>();
    public static final Event<Menu> ON_CONTEXT_MENU_CLOSED = new Event<>();
    public static final Event<Void> ON_SEARCH_REQUESTED = new Event<>();
    public static final Event<SearchEvent> ON_SEARCH_REQUESTED_EVENT = new Event<>();
    public static final Event<Search_Condition> START_SEARCH = new Event<>();
    public static final Event<Query_Bundle> TRIGGER_SEARCH = new Event<>();
    public static final Event<Boolean> TAKE_KEY_EVENTS = new Event<>();
    public static final Event<Void> GET_LAYOUT_INFLATER = new Event<>();
    public static final Event<Theme_Config> ON_APPLY_THEME_RESOURCE = new Event<>();
    public static final Event<String> SHOULD_SHOW_REQUEST_PERMISSION_RATIONALE = new Event<>();
    public static final Event<Void> IS_ACTIVITY_TRANSITION_RUNNING = new Event<>();
    public static final Event<Intent> START_ACTIVITY = new Event<>();
    public static final Event<Intent_Bundle> START_ACTIVITY_OPTIONS = new Event<>();
    public static final Event<Intent[]> START_ACTIVITIES = new Event<>();
    public static final Event<Intents_Bundle> START_ACTIVITIES_OPTIONS = new Event<>();
    public static final Event<IntentSenderConfig> START_INTENT_SENDER = new Event<>();
    public static final Event<IntentSenderConfigWithOptions> START_INTENT_SENDER_OPTIONS = new Event<>();
    public static final Event<IntentRequestCode> START_ACTIVITY_IF_NEEDED = new Event<>();
    public static final Event<IntentRequestCodeOptions> START_ACTIVITY_IF_NEEDED_OPTIONS = new Event<>();
    public static final Event<Intent> START_NEXT_MATCHING_ACTIVITY = new Event<>();
    public static final Event<Intent_Bundle> START_NEXT_MATCHING_ACTIVITY_OPTIONS = new Event<>();
    public static final Event<Activity_Intent_RequestCode> START_ACTIVITY_FROM_CHILD = new Event<>();
    public static final Event<Activity_Intent_RequestCode_Bundle> START_ACTIVITY_FROM_CHILD_OPTIONS = new Event<>();
    public static final Event<Fragment_Intent_RequestCode> START_ACTIVITY_FROM_FRAGMENT = new Event<>();
    public static final Event<Fragment_Intent_RequestCode_Option> START_ACTIVITY_FROM_FRAGMENT_OPTIONS = new Event<>();
    public static final Event<ActivityIntentSenderOption> START_INTENT_SENDER_FROM_CHILD = new Event<>();
    public static final Event<ActivityIntentSenderOptionWithBundle> START_INTENT_SENDER_FROM_CHILD_OPTIONS = new Event<>();
    public static final Event<AnimationDef> OVERRIDE_PENDING_TRANSITION = new Event<>();
    public static final Event<Void> GET_REFERRER = new Event<>();
    public static final Event<Void> ON_PROVIDE_REFERRER = new Event<>();
    public static final Event<Void> GET_CALLING_PACKAGE = new Event<>();
    public static final Event<Void> GET_CALLING_ACTIVITY = new Event<>();
    public static final Event<Boolean> SET_VISIBLE = new Event<>();
    public static final Event<Void> IS_FINISHING = new Event<>();
    public static final Event<Void> IS_DESTROYED = new Event<>();
    public static final Event<Void> IS_CHANGING_CONFIGURATIONS = new Event<>();
    public static final Event<Void> RECREATE = new Event<>();
    public static final Event<Void> FINISH = new Event<>();
    public static final Event<Void> FINISH_AFFINITY = new Event<>();
    public static final Event<Activity> FINISH_FROM_CHILD = new Event<>();
    public static final Event<Void> FINISH_AFTER_TRANSITION = new Event<>();
    public static final Event<Integer> FINISH_ACTIVITY = new Event<>();
    public static final Event<ActivityRequestCode> FINISH_ACTIVITY_FROM_CHILD = new Event<>();
    public static final Event<Void> FINISH_AND_REMOVE_TASK = new Event<>();
    public static final Event<Void> RELEASE_INSTANCE = new Event<>();
    public static final Event<IntentRequestCode> ON_ACTIVITY_REENTER = new Event<>();
    public static final Event<IntentRequestCodeFlags> CREATE_PENDING_RESULT = new Event<>();
    public static final Event<Integer> SET_REQUESTED_ORIENTATION = new Event<>();
    public static final Event<Void> GET_REQUESTED_ORIENTATION = new Event<>();
    public static final Event<Void> GET_TASK_ID = new Event<>();
    public static final Event<Void> IS_TASK_ROOT = new Event<>();
    public static final Event<Boolean> MOVE_TASK_TO_BACK = new Event<>();
    public static final Event<Void> GET_LOCAL_CLASS_NAME = new Event<>();
    public static final Event<Void> GET_COMPONENT_NAME = new Event<>();
    public static final Event<Integer> GET_PREFERENCES = new Event<>();
    public static final Event<String> GET_SYSTEM_SERVICE = new Event<>();
    public static final Event<CharSequence> SET_TITLE = new Event<>();
    public static final Event<Integer> SET_TITLE_ID = new Event<>();
    public static final Event<Integer> SET_TITLE_COLOR = new Event<>();
    public static final Event<ActivityCharSequence> ON_CHILD_TITLE_CHANGED = new Event<>();
    public static final Event<ActivityManager.TaskDescription> SET_TASK_DESCRIPTION = new Event<>();
    public static final Event<Void> IS_IMMERSIVE = new Event<>();
    public static final Event<Boolean> REQUEST_VISIBLE_BEHIND = new Event<>();
    public static final Event<Void> ON_VISIBLE_BEHIND_CANCELED = new Event<>();
    public static final Event<Void> ON_ENTER_ANIMATION_COMPLETE = new Event<>();
    public static final Event<Boolean> SET_IMMERSIVE = new Event<>();
    public static final Event<Boolean_ComponentName> SET_VR_MODE_ENABLED = new Event<>();
    public static final Event<android.view.ActionMode.Callback> START_ACTION_MODE = new Event<>();
    public static final Event<ActionModeCallback_Integer> START_ACTION_MODE_TYPE = new Event<>();
    public static final Event<android.view.ActionMode.Callback> ON_WINDOW_STARTING_ACTION_MODE = new Event<>();
    public static final Event<ActionModeCallback_Integer> ON_WINDOW_STARTING_ACTION_MODE_TYPE = new Event<>();
    public static final Event<android.view.ActionMode> ON_ACTION_MODE_STARTED = new Event<>();
    public static final Event<android.view.ActionMode> ON_ACTION_MODE_FINISHED = new Event<>();
    public static final Event<Intent> SHOULD_UP_RECREATE_TASK = new Event<>();
    public static final Event<Intent> NAVIGATE_UP_TO = new Event<>();
    public static final Event<Activity_Intent> NAVIGATE_UP_TO_FROM_CHILD = new Event<>();
    public static final Event<Void> GET_PARENT_ACTIVITY_INTENT = new Event<>();
    public static final Event<android.app.SharedElementCallback> SET_ENTER_SHARED_ELEMENT_CALLBACK = new Event<>();
    public static final Event<android.app.SharedElementCallback> SET_EXIT_SHARED_ELEMENT_CALLBACK = new Event<>();
    public static final Event<Void> POSTPONE_ENTER_TRANSITION = new Event<>();
    public static final Event<Void> START_POSTPONED_ENTER_TRANSITION = new Event<>();
    public static final Event<DragEvent> REQUEST_DRAG_AND_DROP_PERMISSIONS = new Event<>();
    public static final Event<Void> START_LOCK_TASK = new Event<>();
    public static final Event<Void> STOP_LOCK_TASK = new Event<>();
    public static final Event<Void> SHOW_LOCK_TASK_ESCAPE_MESSAGE = new Event<>();
    public static final Event<Context> ATTACH_BASE_CONTEXT = new Event<>();
    public static final Event<Configuration> APPLY_OVERRIDE_CONFIGURATION = new Event<>();
    public static final Event<Void> GET_ASSETS = new Event<>();
    public static final Event<Void> GET_THEME = new Event<>();
    public static final Event<Void> GET_BASE_CONTEXT = new Event<>();
    public static final Event<Void> GET_PACKAGE_MANAGER = new Event<>();
    public static final Event<Void> GET_CONTENT_RESOLVER = new Event<>();
    public static final Event<Void> GET_MAIN_LOOPER = new Event<>();
    public static final Event<Void> GET_APPLICATION_CONTEXT = new Event<>();
    public static final Event<Void> GET_CLASS_LOADER = new Event<>();
    public static final Event<Void> GET_PACKAGE_NAME = new Event<>();
    public static final Event<Void> GET_APPLICATION_INFO = new Event<>();
    public static final Event<Void> GET_PACKAGE_RESOURCE_PATH = new Event<>();
    public static final Event<Void> GET_PACKAGE_CODE_PATH = new Event<>();
    public static final Event<String_Integer> GET_SHARED_PREFERENCES = new Event<>();
    public static final Event<Context_String> MOVE_SHARED_PREFERENCES_FROM = new Event<>();
    public static final Event<String> DELETE_SHARED_PREFERENCES = new Event<>();
    public static final Event<String> OPEN_FILE_INPUT = new Event<>();
    public static final Event<String_Integer> OPEN_FILE_OUTPUT = new Event<>();
    public static final Event<String> DELETE_FILE = new Event<>();
    public static final Event<String> GET_FILE_STREAM_PATH = new Event<>();
    public static final Event<Void> FILE_LIST = new Event<>();
    public static final Event<Void> GET_DATA_DIR = new Event<>();
    public static final Event<Void> GET_FILES_DIR = new Event<>();
    public static final Event<Void> GET_NO_BACKUP_FILES_DIR = new Event<>();
    public static final Event<String> GET_EXTERNAL_FILES_DIR = new Event<>();
    public static final Event<String> GET_EXTERNAL_FILES_DIRS = new Event<>();
    public static final Event<Void> GET_OBB_DIR = new Event<>();
    public static final Event<Void> GET_OBB_DIRS = new Event<>();
    public static final Event<Void> GET_CACHE_DIR = new Event<>();
    public static final Event<Void> GET_CODE_CACHE_DIR = new Event<>();
    public static final Event<Void> GET_EXTERNAL_CACHE_DIR = new Event<>();
    public static final Event<Void> GET_EXTERNAL_CACHE_DIRS = new Event<>();
    public static final Event<Void> GET_EXTERNAL_MEDIA_DIRS = new Event<>();
    public static final Event<String_Integer> GET_DIR = new Event<>();
    public static final Event<String_Integer_CursorFactory> OPEN_OR_CREATE_DATABASE = new Event<>();
    public static final Event<String_Integer_CursorFactory_DatabaseErrorHandler> OPEN_OR_CREATE_DATABASE_HANDLER = new Event<>();
    public static final Event<Context_String> MOVE_DATABASE_FROM = new Event<>();
    public static final Event<String> DELETE_DATABASE = new Event<>();
    public static final Event<String> GET_DATABASE_PATH = new Event<>();
    public static final Event<Void> DATABASE_LIST = new Event<>();
    public static final Event<Intent> SEND_BROADCAST = new Event<>();
    public static final Event<Intent_String> SEND_BROADCAST_PERMISSION = new Event<>();
    public static final Event<Intent_String> SEND_ORDERED_BROADCAST = new Event<>();
    public static final Event<OrderedBroadcastOption> SEND_ORDERED_BROADCAST_OPTIONS = new Event<>();

}
